package com.llmgateway.model;

public enum LlmStreamEventType {
    MESSAGE_START, CONTENT_BLOCK_START, TEXT_DELTA, THINKING_DELTA, CONTENT_BLOCK_END,
    TOOL_CALL_START, TOOL_CALL_DELTA,
    TOOL_CALL_END, USAGE, MESSAGE_END, ERROR
}
