"""Exercise a real SDK against streams generated by the gateway, without network calls."""

import argparse
import json
from pathlib import Path

import anthropic
import httpx2


def verify(fixtures: Path) -> None:
    cases = json.loads(fixtures.read_text())
    for case in cases:
        def upstream(request: httpx2.Request) -> httpx2.Response:
            assert request.url.path == "/v1/messages"
            return httpx2.Response(200, headers={"content-type": "text/event-stream"}, content=case["stream"].encode())

        with anthropic.Anthropic(api_key="synthetic-sdk-key", max_retries=0,
                                 http_client=httpx2.Client(transport=httpx2.MockTransport(upstream))) as client:
            with client.messages.stream(model="fixture-model", max_tokens=16,
                                        messages=[{"role": "user", "content": "synthetic input"}]) as stream:
                message = stream.get_final_message()
        assert message.usage.input_tokens == case["input_tokens"], case["name"]
        assert message.usage.output_tokens == case["output_tokens"], case["name"]
        assert message.content[0].text == "synthetic answer", case["name"]
        assert message.stop_reason == ("tool_use" if case["tool"] else "end_turn"), case["name"]
        if case["tool"]:
            assert message.content[1].id == "fixture-call", case["name"]
            assert message.content[1].input == {"value": 1}, case["name"]
    print(f"SDK compatibility passed: {len(cases)} streaming cases with anthropic {anthropic.__version__}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixtures", type=Path, default=Path(__file__).resolve().parents[1] / "backend/build/sdk-fixtures/anthropic.json")
    verify(parser.parse_args().fixtures)
